### ISSUE TITLE
Can't select colors

### ISSUE THREAD

**Issue by Akillz1337** [RoootTheFox/custom-gamemode-colors#3]
Clicking on the color palette has no effect, it only lets me choose the gamemodes, which makes them default green color and that's it. Reinstalled the game, reinstalled the mod, cleared appdata folder, tried to disable all other mods, except NodeIds of course, but nothing seems to work. Do you know possible fix? (Windows steam version)

**Comment by Akillz1337** [comment]
Windows steam version btw

**Comment by RoootTheFox** [comment]
the gray/green buttons at the top toggle which overrides are enabled (if its disabled/gray, the mod won't do anything)

if you want to change the colors for a gamemode, click its sprite (cube, ship, etc) and then use the color palette.

did you do that or did you not click a player icon?

**Comment by Akillz1337** [comment]
Yes, override buttons work, that's what i meant by "it only lets me choose the gamemodes" and icons turn green color in menu and gameplay, but i cant select any other color on the palette.

**Comment by RoootTheFox** [comment]
Does it show the selection box around the gamemode you're trying to edit?

**Comment by Akillz1337** [comment]
Oh, my bad, i didn't know you also had to click the icons themselves, haven't read the mod description thoroughly enough, thanks for clarifying.

**Comment by RoootTheFox** [comment]
to be fair, i should probably make this more clear in the UI. i'll work on that in a future update ^^
