### ISSUE TITLE
Separate Dual Icons compatibility

### ISSUE THREAD

**Issue by Lost0032** [RoootTheFox/custom-gamemode-colors#6]
the mod is not working with mod called "separate dual icons" please fix this i cant live without that mod

**Comment by RoootTheFox** [comment]
support/compatibility with separate dual icons is planned, will be implemented once I implement dual colors.

**Comment by RoootTheFox** [comment]
wanted to give a small update on this, i started to refactor/rewrite some code and add initial Separate Dual Icons compatibility - its not finished yet though
see the [`2player`](https://github.com/RoootTheFox/custom-gamemode-colors/tree/2player) branch
